
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      - name: Install
        run: sudo make
      - name: Test
        run: sudo ./venv/bin/python3 ftpserver.py -t
